[project]
name = "ai-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "errajibadr", email = "errajibadr95@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "langchain[openai]>=0.3.27",
    "langgraph>=0.6.6",
    "pydantic-settings>=2.10.1",
    "core",
    "langgraph-checkpoint-sqlite>=2.0.11",
    "langchain-google-vertexai>=2.0.28",
    "aiosqlite>=0.21.0",
]

[project.scripts]
ai-engine = "ai_engine:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

