[project]
name = "ai-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "errajibadr" }
]
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "langchain[openai]>=0.3.27",
    "langgraph>=0.6.6",
    "pydantic-settings>=2.10.1",
    "core",
    "langgraph-checkpoint-sqlite>=2.0.11",
    "langchain-google-vertexai>=2.0.28",
    "aiosqlite>=0.21.0",
    "langchain-mcp-adapters>=0.1.9",
    "langchain-community>=0.3.29", # Scraping website for RAG document_loaders.sitemap import SitemapLoader
    "lxml>=6.0.1", # Scraping website for RAG
    "bs4>=0.0.2", # Scraping website for RAG
    "scikit-learn>=1.7.2", # Only used for Vector DB
]

[project.scripts]
ai-engine = "ai_engine:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "tavily-python>=0.7.11",
]

