[project]
name = "frontend"
version = "0.1.0"
description = "Streamlit frontend for multi-provider LLM chat interface"
readme = "README.md"
authors = [
    { name = "errajibadr", email = "errajibadr95@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.28.0",
    "requests>=2.31.0",
    "python-dotenv>=1.0.0",
    "ai-engine",
    "core",
]

[project.scripts]
frontend = "frontend:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

