[project]
name = "core"
version = "0.1.0"
description = "Core business logic, models, and shared utilities"
readme = "README.md"
authors = [
    { name = "errajibadr"}
]
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.0.0",
    "pydantic-settings>=2.0.0",
    "python-dotenv>=1.0.0",
    "elasticsearch[async]>=8.17.0",
    "asyncpg>=0.30.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
